In [37]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import random
import numpy as np
import math
import warnings
import missingno as msno
from pprint import pprint
from chinese_calendar import is_workday, is_holiday
from pathlib import Path
from sklearn.preprocessing import PowerTransformer
import scipy.stats as st
from collections import defaultdict

# 固定随机种子，稳定模型效果
random.seed(2021) 
np.random.seed(2021)
%matplotlib inline
warnings.filterwarnings("ignore")
plt.rc("font",family="SimHei",size="10")
plt.rcParams['axes.unicode_minus']=False
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('max_colwidth',200)
pd.set_option('expand_frame_repr', False)

In [38]:
root = Path(os.getcwd()).resolve().parent / "data"
q2_df = root / "附件4：门店交易训练数据.txt"
train = root / "附件1：估价训练数据.txt"
i2n = ["carid", "pushDate", "pushPrice", "updatePriceTimeJson", "pullDate", "withdrawDate"]

index2name = ["carid", "展销时间", "品牌 id", "车系 id", "车型 id", "里程", "车辆颜色", "车辆所在城市 id", "国标码",
              "过户次数", "载客人数", "注册日期", "上牌日期", "国别", "厂商类型", "年款", "排量", "变速箱", "燃油类型",
              "新车价"]

# category存放的是类别特征的名称
category = ["品牌 id", "车系 id", "车型 id", "车辆颜色", "车辆所在城市 id", "厂商类型", "燃油类型"] # 类别类型特征

# numerical存放的是数值特征的名称
numerical = ["Feature_5", "年款", "排量", "变速箱", "Feature_2", "Feature_13", "载客人数", "新车价", "里程", "target"] #  "厂商类型"实数类型特征, "Feature_12", "Feature_8"

# cross_num存放的是要进行特征交叉的特征的名称
cross_num = ["新车价", "Feature_2", "Feature_12_1"]

# 匿名特征为Feature_i，此处将15个匿名特征加入到index2name中
for _ in range(1, 16):
    index2name.append("Feature_"+str(_))
index2name.append("target")
def __i2n(df):
    df = df.rename(columns={index: _ for index, _ in enumerate(index2name)})
    return df

In [39]:
q2 = pd.read_csv(q2_df, sep='\t', header=None)
q2.rename(columns={index: _ for index, _ in enumerate(i2n)}, inplace=True)

In [40]:
train_df = pd.read_csv(train, sep='\t', header=None)
train_df = __i2n(train_df)

In [41]:
len(q2)

10000

In [42]:
len(q2[q2["pullDate"] != q2["withdrawDate"]])

2000

In [43]:
result = pd.merge(q2, train_df, left_on="carid", right_on="carid", how="left")

In [44]:
result["展销时间"] = pd.to_datetime(result["展销时间"])
result["注册日期"] = pd.to_datetime(result["注册日期"])
result["上牌日期"] = pd.to_datetime(result["上牌日期"])
result["pushDate"] = pd.to_datetime(result["pushDate"])
result["pullDate"] = pd.to_datetime(result["pullDate"])
result["withdrawDate"] = pd.to_datetime(result["withdrawDate"])

In [45]:
result["成交周期"] = (result["withdrawDate"] - result["pushDate"]).map(lambda x: x.days)

In [46]:
result.head()

   carid   pushDate  pushPrice     updatePriceTimeJson   pullDate withdrawDate       展销时间  品牌 id  车系 id  车型 id     里程  车辆颜色  车辆所在城市 id  国标码  过户次数  载客人数       注册日期       上牌日期        国别  厂商类型      年款   排量   变速箱  燃油类型    新车价  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6   Feature_7  Feature_8  Feature_9  Feature_10 Feature_11      Feature_12  Feature_13  Feature_14  Feature_15   target  成交周期
0  68603 2021-03-11     3.9800                      {} 2021-03-11   2021-03-11 2021-03-11     47    314  11903  11.80     1          1  2.0     1     5 2013-10-01 2013-11-08  779414.0   2.0  2014.0  1.8   3.0     1  15.89        1.0          2          2        NaN         51          2  2018-03-09        1.0        4.0         3.0        1+2  4620*1780*1498    201311.0           1         NaN   3.9800   0.0
1  12312 2021-05-14     4.5000                      {} 2021-06-14   2021-06-14 2021-05-14     62    797   3174   3.87     4          2  1.0     0     5 2017-09-01 2017-11-14  779413.0   1.0  2017.0  1.4  23.0     1   9.28        1.0          1          2      632.0         71          1         NaN        2.0        5.0         2.0          1  4195*1780*1622    201709.0           2         NaN   4.5000  31.0
2  57655 2021-03-13    23.9000    {"2021-04-05": "23"} 2021-04-08   2021-04-08 2021-04-05      8    196  10320   1.64     2          3  4.0     1     5 2019-05-01 2019-11-08  779412.0   1.0  2019.0  2.0   7.0     1  34.00        1.0          8          2      981.0         10          2  2021-03-13        2.0        4.0         NaN          1  5074*1893*1489    201901.0           2         NaN  23.0000  26.0
3  45688 2020-09-01    20.5798                      {} 2020-09-04   2020-09-04 2020-09-01     42    845   8504  10.45     6          1  2.0     0     2 2010-09-01 2010-11-29  779412.0   3.0     NaN  2.9  31.0     1  82.13        1.0         13          2        NaN         43         13         NaN        1.0        2.0         2.0        1+2  4342*1801*1292    201102.0           1  2023-08-31  20.5798   3.0
4  52081 2021-04-29    12.2800  {"2021-05-20": "11.9"} 2021-06-21   2021-06-21 2021-05-20      2    187   9521   5.66     6         19  2.0     1     5 2014-10-01 2014-12-12  779415.0   2.0  2013.0  2.0  11.0     1  22.98        1.0          5          2      554.0          2          1  2015-11-07        1.0        5.0         2.0        1+2  4570*1845*1670    201308.0           1         NaN  11.9000  53.0

In [47]:
result.to_csv(root / "Q3.csv", index=None)